SHOW DATABASES; 
CREATE DATABASE College;
SHOW DATABASES; 
USE College;
SHOW TABLES;
-- Create STUDENT table
CREATE TABLE STUDENT (
    RollNo CHAR(6) PRIMARY KEY,
    StudentName VARCHAR(20) NOT NULL,
    Course VARCHAR(10),
    DOB DATE
);
-- Create SOCIETY table
CREATE TABLE SOCIETY (
    SocID CHAR(6) PRIMARY KEY,
    SocName VARCHAR(20) NOT NULL,
    MentorName VARCHAR(15),
    TotalSeats INT UNSIGNED
);
-- Create ENROLLMENT table
CREATE TABLE ENROLLMENT (
    RollNo CHAR(6),
    SID CHAR(6),
    DateOfEnrollment DATE,
    PRIMARY KEY (RollNo, SID),
    FOREIGN KEY (RollNo) REFERENCES STUDENT(RollNo),
    FOREIGN KEY (SID) REFERENCES SOCIETY(SocID)
);
SHOW TABLES;
DESC STUDENT;
DESC SOCIETY;
DESC ENROLLMENT;
