UPDATE ENROLLMENT
SET DateOfEnrollment = '2018-01-15'
WHERE SID = 's1';
UPDATE ENROLLMENT
SET DateOfEnrollment = CURRENT_DATE()
WHERE SID = 's2';
UPDATE ENROLLMENT
SET DateOfEnrollment = '2018-01-02'
WHERE SID = 's3';
SELECT * FROM ENROLLMENT;
