SELECT S.StudentName,S.DOB
FROM STUDENT S
JOIN ENROLLMENT E ON S.RollNo = E. RollNo
JOIN SOCIETY SO ON E.SID = SO.SocID
WHERE SO.SocName = 'NSS'; -- students who are in nss

SELECT S.StudentName
FROM STUDENT S
JOIN ENROLLMENT E ON S.RollNo = E.RollNo
JOIN SOCIETY SO ON E.SID = SO.SocID
WHERE SO.SocName = 'NSS'
AND S.DOB = (
    SELECT MAX(S2.DOB)
    FROM STUDENT S2
    JOIN ENROLLMENT E2 ON S2.RollNo = E2.RollNo
    JOIN SOCIETY SO2 ON E2.SID = SO2.SocID
    WHERE SO2.SocName = 'NSS'
);
